### ISSUE TITLE
Documentation request: How to use ruby-xxHash on large files

### ISSUE THREAD

**Issue by brandonzylstra** [justinwsmith/ruby-xxhash#1]
Is there a method for generating a hash from a large (multi-GB) file?  With text it is easy enough to use a less efficient algorithm, but xxHash shines with humungous files, like disk images and such.

**Comment by justinwsmith** [comment]
You should be able to use the "stream" function:

```
    XXhash.xxh64_stream(File.open(path_to_really_big_file), 123)
```

You can see tests for these in spec/xxhash_spec.rb
